CREATE TABLE `users` (
  `id` VARCHAR(50) NOT NULL,
  `username` VARCHAR(30) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `firstname` VARCHAR(30) DEFAULT NULL,
  `surname` VARCHAR(30) DEFAULT NULL,
  `picture` VARCHAR(30) DEFAULT NULL,
  `acc_type` VARCHAR(30) NOT NULL,
  `create_at` VARCHAR(30) NOT NULL,
  `update_at` VARCHAR(30) NOT NULL,
  `active` VARCHAR(30) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;